version: '3.8'

services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    restart: always
    volumes:
      - ./web:/var/www/html
    ports:
      - "80:80"
  wordpress:
    build: requirements/wordpress/
    container_name: wp-php
    restart: always
    volumes:
      - ./web:/var/www/html
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - main_network
    env_file:
      - .env

networks:
  main_network: