version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
    restart: always
    networks: 
      - main_network
  mariadb:
    container_name: mariadb
    image: mariadb
    build: requirements/mariadb/
    volumes:
      - ./database:/var/lib/mysql
    restart: always
    networks:
      - main_network
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    build: requirements/wordpress/
    restart: always
    volumes:
      - ./web:/var/www/html
    env_file:
      - .env
    networks:
      - main_network


networks:
  main_network: