version: '3.8'

services:
  nginx:
    image: nginx
    build: 
      context: ./requirements/nginx
    container_name: nginx
    restart: on-failure
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    env_file: .env
    networks:
      - main_network

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MYSQL_DB=${MYSQL_DB}
        - MYSQL_PASS=${MYSQL_PASS}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_ROOT_PASS=${MYSQL_ROOT_PASS}
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mariadb
    restart: always
    networks:
      - main_network
    env_file: .env

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    expose:
      - "9000"
    restart: always
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - main_network
      
networks:
  main_network:
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_PATH}/web
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_PATH}/database