version: '3.8'

services:
  nginx:
    image: nginx
    build: requirements/nginx/
    container_name: nginx
    restart: on-failure
    depends_on:
      - wordpress
    volumes:
      - web:/var/www/html
    ports:
      - "443:443"
    env_file: .env
    networks:
      - main_network
  mariadb:
    image: mariadb
    build:
      dockerfile: Dockerfile
      context: requirements/mariadb/
      args:
        - MYSQL_DB_NAME=${MYSQL_DB_NAME}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASS=${MYSQL_PASS}
        - MYSQL_ROOT_PASS=${MYSQL_ROOT_PASS}
    container_name: mariadb
    restart: on-failure
    expose:
      - "3306"
    volumes:
      - database:/var/lib/mysql
    networks:
      - main_network
    env_file:
      - .env
  wordpress:
    image: wordpress
    build: requirements/wordpress/
    container_name: wordpress
    depends_on:
      - mariadb
    expose:
      - "9000"
    restart: on-failure
    volumes:
      - web:/var/www/html
    env_file:
      - .env
    networks:
      - main_network

networks:
  main_network:
    driver: bridge

volumes:
web:
  name: web
  driver: local
  driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_PATH}/web
  database:
    name: database
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUME_PATH}/database
